version: '3'

services:
  db-archive-server:
    image: db-archive-server:latest
    container_name: db-archive-server
    ports:
      - "${DB_ARCHIVE_SERVER_PORT}:8080"
    volumes:
      - ${DB_ARCHIVE_SERVER_ROOT}:/usr/share/nginx/html
    environment:
      - NGINX_PORT=8080
